# Generated by Django 4.2.2 on 2023-08-12 05:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Information",
            fields=[
                (
                    "camera",
                    models.AutoField(
                        help_text="할당된 CAM 번호(PK)", primary_key=True, serialize=False
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        default="", help_text="목줄 미착용 시 저장되는 이미지", upload_to=""
                    ),
                ),
                (
                    "dateTime",
                    models.DateTimeField(
                        auto_now=True, help_text="목줄 미착용 시 저장되는 DateTime"
                    ),
                ),
                ("prob_dog", models.FloatField(help_text="객체가 개일 확률")),
                ("prob_leash", models.FloatField(help_text="목줄 착용 확률")),
                (
                    "location",
                    models.CharField(help_text="ex. 서울시 금천구 가산동", max_length=100),
                ),
                (
                    "add",
                    models.CharField(
                        default="위치 보조 지표 없음",
                        help_text="ex. (전)100P_032",
                        max_length=100,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-dateTime",),
            },
        ),
    ]
